### ISSUE TITLE
oneonone/channel.go:74","msg":"unable to connect to remote peer"

### ISSUE THREAD

**Issue by ppt93** [berty/go-orbit-db#107]
oneonone/channel.go 74 line 

```
if err := c.ipfs.Swarm().Connect(ctx, peer.AddrInfo{ID: target}); err != nil {
		c.logger.Warn("unable to connect to remote peer", zap.String("peer", target.String()))
}
```

 peer.AddrInfo has 2 params.Only one param cause "argument "address" is required' bug。

**Comment by peletron** [comment]
@ppt93 thanks for reporting of issue. We will take a look and get back to you as soon as possible.

**Comment by gfanton** [comment]
@ppt93 the only parameter required here is the `ID`, `Addrs` is optional.

Connect method will:
1. add the given `Addrs` from `AddrInfo` (if provided) to the `Peerstore` 
2. retrieve all `Addrs` from the `Peerstore`
3. if no `Addrs` is found it will try to run a find peers with the given discovery service (on a routed host only)
4. use those `Addrs` to connect

At this point, the pubsub discovery mechanism should already have added all the necessary `Addrs` in the `PeerStore` to successfully connect.

**Comment by ppt93** [comment]
I understand what you mean. That's right

**Comment by peletron** [comment]
@gfanton  Thanks for follow up. Hope this helps @ppt93  :) 

Closing this issue
