### ISSUE TITLE
Implement HTTP API (or grpc)

### ISSUE THREAD

**Issue by sgmihai** [berty/go-orbit-db#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature request

I am suggestin adding a HTTP or gRPC API interface so that we can use go-orbit-db from any programming/scripting language.

### Context

It would be nice to be able to use this project from any programming language, not just Go.
orbitdb and its http api has fallen out of maintenance, you can only use it with ancient ipfs versions.

**Comment by jefft0** [comment]
Hello @sgmihai . We do not have plans for major updates to go-orbit-db like this. Is it critical for your project? Otherwise, we can close this issue as "won't implement".

**Comment by jefft0** [comment]
No more comments from the poster. Closing as won't implement.
