### ISSUE TITLE
Upgrade kubo

### ISSUE THREAD

**Issue by wenyue** [berty/go-orbit-db#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature request

Do we have a plan to update the kubo, it's a bit too old.

### Context

Do we have a plan to update the kubo, it's a bit too old.

**Comment by MichaelJCole** [comment]
Hi, I'm a go newbie.  I'm evaluating go-orbit-db for a new project.  

Has [Kubo already been upgraded here](https://github.com/berty/go-orbit-db/compare/master...stateless-minds:go-orbit-db:master)?

This looks like a single library function.  How is it meant to be used?  Will it work with the newest Kubo version in a plugin?

Thank you,

**Comment by jefft0** [comment]
We also need to update libp2p. https://github.com/berty/berty/issues/4799 So we will update kubo at the same time.

**Comment by jefft0** [comment]
> Hi, I'm a go newbie. I'm evaluating go-orbit-db for a new project.
> 
> Has [Kubo already been upgraded here](https://github.com/berty/go-orbit-db/compare/master...stateless-minds:go-orbit-db:master)?
> 
> This looks like a single library function. How is it meant to be used? Will it work with the newest Kubo version in a plugin?
> 
> Thank you,

Hi @MichaelJCole . Can you open a separate issue with your question? Thank you.

**Comment by MichaelJCole** [comment]
Hi @jefft0 I gave up on Kubo.

Kubo has 47 repo's and is a total mess of a code base.

Thanks for the offer though.

**Comment by jefft0** [comment]
Hello @wenyue . Thanks to work by @D4ryl00 , go-orbit-db is now upgraded to the latest version v0.29.0 of kubo. Does this resolve your issue?

**Comment by jefft0** [comment]
The go-orbit-db upgrade was completed. No more questions from poster. Closing.
