### ISSUE TITLE
orbitdb vs go-ds-crdt

### ISSUE THREAD

**Issue by pkieltyka** [berty/go-orbit-db#145]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

hi, I was wondering if you team has seen / explored https://github.com/ipfs/go-ds-crdt ? It has a similar merkle crdt design and achieves similar properties by leverages IPLD. I was wondering if anyone has explored it, if they have any thoughts on pros/cons for approaches..?

### Context

deciding between libraries / approaches

**Comment by jefft0** [comment]
Thanks for bringing this to our attention. No, we are not familiar with go-ds-crdt, so we can't advise you. However, we can consider this for possible future upgrades.

**Comment by jefft0** [comment]
No more comments. Closing.
