### ISSUE TITLE
Can not install go-orbit-db

### ISSUE THREAD

**Issue by gasparyanyur** [berty/go-orbit-db#16]
Hi @moul

I am trying to install `github.com/berty/go-orbit-db by the command`
`go get github.com/berty/go-orbit-db`
and as a response I am getting an error look like this
```
go: github.com/berty/go-orbit-db@v0.0.1: parsing go.mod: unexpected module path "berty.tech/go-orbit-db"
go: error loading module requirements
```
I also tried to get package by the command
`go get -u github.com/berty/go-orbit-db@master`
and also got the same error.

Can you help me solve this issue ?

**Comment by moul** [comment]
Hi @gasparyanyur 

We just updated our install documentation in #17

Can you give a new try by following what's suggested in the README.md file?

Thank you for your feedback :+1:

**Comment by gasparyanyur** [comment]
Here is my go.mod file 
```
module main

go 1.13

replace berty.tech/go-orbit-db => github.com/berty/go-orbit-db v1.2.0

require github.com/berty/go-orbit-db v1.2.0
``` 
And here is an error

```console
go: github.com/berty/go-orbit-db@v1.2.0: parsing go.mod:
        module declares its path as: berty.tech/go-orbit-db
                but was required as: github.com/berty/go-orbit-db


```

**Comment by burdiyan** [comment]
You should import it as berty.tech/go-orbit-db. If you want to use github.com import try this replace directive instead:

```
module main

go 1.13

replace github.com/berty/go-orbit-db => berty.tech/go-orbit-db v1.2.0

require github.com/berty/go-orbit-db v1.2.0
```
