### ISSUE TITLE
Nodes do not receive data

### ISSUE THREAD

**Issue by gasparyanyur** [berty/go-orbit-db#46]
Hi all. 
For a long time, I use OrbitDb as a sync transport. So, today I found that some nodes do not receive any data that has been published a few minutes ago.
In my case, there are 3 nodes that publish entries in an endless loop, and in the end, it turns out that one node does not receive any data.
Please help solve this problem and tell me please what could be the problem?

**Comment by glouvigny** [comment]
Hi, it seems we have multiple issues being worked on the latest master, can't you use an earlier version in the meantime?

**Comment by jefft0** [comment]
Hello @gasparyanyur. There have been several releases of go-orbit-db since you posted your issue. Has it been resolved?

**Comment by jefft0** [comment]
Closing for inactive. If you still an issue, feel free to open a new issue. Thank you.
