### ISSUE TITLE
some question about replication, delete data entity, and access over intertnet

### ISSUE THREAD

**Issue by bitcard** [berty/go-orbit-db#47]
1, does support replicaiton among nodes? If yes, will it sync all data to all node? or have replication factor, for example, factor is 5, then data will repliction to 5 node?
2, orbit-db base on ipfs-log, it's Append-only log, It can't delete data entity, does go-orbit-db can delete entity?
3, over global internet, can it write one node and read another node ?
thanks.

**Comment by glouvigny** [comment]
Hi, go-orbit-db is based on a JS project called [OrbitDB](https://github.com/orbitdb), you will find architectural information on OrbitDB's [field manual](https://github.com/orbitdb/field-manual).

1. I am not sure to understand your question. All data is replicated among all nodes, no sharding is possible.
2. IPFS Log is a unmutable, append only log. You can't indeed delete any data on the underlying storage. However, you can perform "soft-delete" operations. You have to manage it at the store level. A port of the JS [FeedStore](https://github.com/orbitdb/orbit-db-feedstore) would be a good start.
3. All nodes will exchange and synchronize their stores either on local network or on the internet.

**Comment by bitcard** [comment]
> Hi, go-orbit-db is based on a JS project called [OrbitDB](https://github.com/orbitdb), you will find architectural information on OrbitDB's [field manual](https://github.com/orbitdb/field-manual).
> 
> 1. I am not sure to understand your question. All data is replicated among all nodes, no sharding is possible.
> 2. IPFS Log is a unmutable, append only log. You can't indeed delete any data on the underlying storage. However, you can perform "soft-delete" operations. You have to manage it at the store level. A port of the JS [FeedStore](https://github.com/orbitdb/orbit-db-feedstore) would be a good start.
> 3. All nodes will exchange and synchronize their stores either on local network or on the internet.

thanks for your reply, I got it about go-orbit-db.
