### ISSUE TITLE
Test failed when run all tests repeatedly

### ISSUE THREAD

**Issue by phanhuynhquy** [berty/go-orbit-db#63]
when run all tests repeatedly like
`go test -race -count=100 -v ./... 2>&1 | tee test_output.txt`

There are several issues: (see [test_report.zip](https://github.com/berty/go-orbit-db/files/5040964/test_report.zip) for logs)

**1.  test timed out** (maybe golang test error)
- === RUN   TestPersistence
=== RUN   TestPersistence/loads_database_from_local_cache
=== RUN   TestPersistence/loads_database_partially
=== RUN   TestPersistence/load_and_close_several_times
=== RUN   TestPersistence/closes_database_while_loading
=== RUN   TestPersistence/load,_add_one,_close_-_several_times
panic: test timed out after 10m0s

**2. TestReplication/replicates_database_of_10_entries_with_node_type_default failed**

=== RUN   TestReplication/replicates_database_of_1_entries_with_node_type_direct-channel
=== RUN   TestReplication/replicates_database_of_10_entries_with_node_type_default
    replicate_test.go:78: 
        	Error Trace:	replicate_test.go:78
        	            				replicate_test.go:201
        	Error:      	Not equal: 
        	            	expected: 10
        	            	actual  : 9
        	Test:       	TestReplication/replicates_database_of_10_entries_with_node_type_default
=== RUN   TestReplication/replicates_database_of_10_entries_with_node_type_direct-channel
=== RUN   TestReplication/replicates_database_of_10_entries_with_node_type_raw-pubsub
--- FAIL: TestReplication (38.79s)
    --- PASS: TestReplication/replicates_database_of_1_entries_with_node_type_raw-pubsub (7.88s)
    --- PASS: TestReplication/replicates_database_of_1_entries_with_node_type_default (5.24s)
    --- PASS: TestReplication/replicates_database_of_1_entries_with_node_type_direct-channel (3.41s)
    --- FAIL: TestReplication/replicates_database_of_10_entries_with_node_type_default (11.70s)

**PS:**
coveragereport:
[coverage.zip](https://github.com/berty/go-orbit-db/files/5040971/coverage.zip)

**Comment by aeddi** [comment]
Hello 👋 
Thank you for your input.

We are currently investigating consistency problems on go-orbit-db and go-ipfs-log that cause bugs in the Berty Protocol. 

It's probably related, we'll update your issue if we fix bugs mentioned here. Don't hesitate if you have time and the desire to fix things on your side! ;)
