### ISSUE TITLE
[Feature Request] Add `Pin` option for Store operations

### ISSUE THREAD

**Issue by hmqgg** [berty/go-orbit-db#82]
Per [Orbit DB Store / Private Methods / _addOperation](https://github.com/orbitdb/orbit-db-store#private-methods), there is an option that controls the `Store` behavior: Pin a document or not. Furthermore, that option pass to public methods of `Store` implementations such as `DocumentStore`.

But in this Golang fork, we do not have a switch in `BaseStore.AddOperation` to pin it.

This feature is vital for the production scenario.

**Comment by jefft0** [comment]
Hello @hmqgg . Actually, we are working on simplifying this library to use libp2p directly without IPFS. So, the IPFS pin functionality won't be available. We hope you can find another workaround for your issue. We plan to close this feature request.

**Comment by jefft0** [comment]
No more comments from the poster. Closing as won't implement.
